homeassistant: !include config/homeassistant.yaml

frontend:
config:
updater:
discovery:
conversation:
history:
logbook:
map:

group: !include_dir_merge_named config/groups
automation: !include_dir_list config/automations
sensor: !include_dir_list config/sensors
script: !include config/scripts.yaml
tts: !include config/tts.yaml
panel_iframe: !include config/panel_iframe.yaml