homeassistant: !include config/homeassistant.yaml

frontend:
config:
updater:
discovery:
conversation:
history:
logbook:
map:

sensor: !include_dir_list config/sensors
group: !include_dir_merge_named config/groups
automation: !include_dir_list config/automations
script: !include config/scripts.yaml
tts: !include config/tts.yaml